--select * from SWOGRAVE.CORETB_BTA_NONTARGET_L where S0ASSCD = '99';
--select * from SWOGRAVE.CORETB_BTA_TARGET_L where L0ASSCD = '99';
--select * from SWOGRAVE.CORETB_FUTA_NONTARGET_L where S0ASSCD = '99';
--select * from SWOGRAVE.CORETB_FUTA_TARGET_L where L0ASSCD = '99';
--select * from SWOGRAVE.PROGLUNG where DOTHSIT = '1';
--select * from SWOGRAVE.PROGLUNG where DOTHSIT = '1' and OTHSPEC like '%chest%';

--select CORETB_FUTA_NONTARGET_L.PATNO, CORETB_FUTA_NONTARGET_L.S0ASSCD, CORETB_FUTA_NONTARGET.CMT
--FROM CORETB_FUTA_NONTARGET_L
--INNER JOIN CORETB_FUTA_NONTARGET
--ON CORETB_FUTA_NONTARGET_L.PATNO = CORETB_FUTA_NONTARGET.PATNO
--WHERE S0ASSCD = '99' and CMT LIKE '%%';

select * from SWOGPART11.PROGLUNG where DOTHSIT = '1' and OTHSPEC like '%%';